spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1444;databaseName=reports;TrustServerCertificate=True
    username: sa
    password: P@ssw0rd
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger
    displayRequestDuration: true
    tryItOutEnabled: true
    groupsOrder: DESC
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-doc